baseURL = "https://jovial-blackwell-fc9211.netlify.app/"
#linkURL = "https://jamestowens.com"
languageCode = "en-us"
title = "Jim Owens"
theme = "ink"
paginate = 5

copyright = "Â© 2020 by Jim Owens"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-174218328-1"
#disqusShortname = "ink-demo"

[params]
	#subtitle = "Chemical Engineering Grad Student @ MIT, [[cv]](CV.pdf)"
	subtitle = "Chemical Engineering Grad Student @ MIT, [[cv]](https://jamestowens.com/CV.pdf)"

	# Optional 64x64 avatar image.
	avatar = "https://jamestowens.com/avatar_head.jpg"
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 2

[[menu.main]]
name = "Good Reads"
url = "/tags"
weight = 4









[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/JimOwens96"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jt-owens/" 

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:jtowens@mit.edu"

[taxonomies]
   tag = "tags"
